<?php

//genereert de afbeeldingen van de pdf

use Drupal\Core\Entity\EntityInterface;
use Drupal\imagemagick\Plugin\ImageToolkit\ImagemagickToolkit;


function pdfpreview_theme($existing, $type, $theme, $path) {
  return array(
    'pdfpreview_formatter' => array(
      'render element' => 'element',
    ),
  );
}

function pdfpreview_file_update(EntityInterface $file) {
  \Drupal::service('pdfpreview.generator')->updatePDFPreview($file);
}

function pdfpreview_file_delete(EntityInterface $file) {
  \Drupal::service('pdfpreview.generator')->deletePDFPreview($file);
}


function pdfpreview_imagemagick_arguments_alter(ImagemagickToolkit $toolkit, $command) {
  $i = $toolkit->findArgument('-pdfpreview');
  if ($i !== FALSE) {
    $toolkit->removeArgument($i);
    $toolkit->setSourceLocalPath($toolkit->getSourceLocalPath() . '[0]');
  }
}
//gebruikt de default template 
function template_preprocess_pdfpreview_formatter(&$variables) {
  $settings = $variables['element']['#settings'];
  $variables['tag'] = $settings['tag'];
  $variables['fid'] = $variables['element']['#fid'];
  $variables['description'] = $settings['show_description'] ? $variables['element']['#description'] : '';
}
